#!/bin/bash

query="$@"

function job {
    echo "${fn}"
    IFS=$'\t' read -r -a myArray < <(echo "$1")
    fn="${myArray[0]}"

    for duplicate in "${myArray[@]:1}"
    do
        rm -rf "${duplicate}"
        ln "${fn}" "${duplicate}"
    done
}
export -f job

notmuch show \
        --format=json \
        --entire-thread=false \
        --body=false \
        "${query}" | \
    jq -n \
       --stream \
       'fromstream(1 | truncate_stream(inputs))' | \
    jq -r '.. | .filename? //empty | @tsv' | \
    parallel -j4 job | \
    pv -l -s $(notmuch count "${query}") > /dev/null
